use std::{collections::HashMap, path::Path};
macro_rules! map {
  ( [ $( ( $key:expr, $value:expr ) ),+ ] ) => {
        {
            let mut map = ::std::collections::HashMap::new();
            $(map.insert($key, $value);)+
            map
        }
    }
}

pub const NUM_ITEMS: i32 = 732;

lazy_static! {
    pub static ref ITEM_DESCRIPTIONS: HashMap<i32, &'static str> = map!([
        (1_i32, "Tears up"),
        (2, "Triple shot"),
        (3, "Homing shots"),
        (4, "DMG up"),
        (5, "Boomerang tears"),
        (6, "Tears up + range down"),
        (7, "DMG up"),
        (8, "Friends 'till the end"),
        (9, "Fly love"),
        (10, "Projectile protection"),
        (11, "Extra life"),
        (12, "All stats up!"),
        (13, "Poison touch + speed up"),
        (14, "Speed and range up"),
        (15, "HP up"),
        (16, "HP up"),
        (17, "99 keys"),
        (18, "$$$"),
        (19, "10 bombs"),
        (20, "We all float down here..."),
        (21, "The end is near"),
        (22, "HP up"),
        (23, "HP up"),
        (24, "HP up"),
        (25, "HP up"),
        (26, "HP up"),
        (27, "Speed up"),
        (28, "Speed up"),
        (29, "Range up"),
        (30, "Range up"),
        (31, "Range up"),
        (32, "Tears up"),
        (33, "Temporary flight"),
        (34, "Temporary DMG up"),
        (35, "Mass room damage"),
        (36, "Plop!"),
        (37, "Reusable bomb buddy"),
        (38, "Reusable tear burst"),
        (39, "Mass paralysis"),
        (40, "Become the bomb!"),
        (41, "Mass fear"),
        (42, "Reusable ranged bomb"),
        (44, "Teleport!"),
        (45, "Reusable regeneration"),
        (46, "Luck up"),
        (47, "Reusable air strike"),
        (48, "Piercing shots"),
        (49, "BLLLARRRRGGG!"),
        (50, "DMG up"),
        (51, "DMG up"),
        (52, "???"),
        (53, "Item snatcher"),
        (54, "Full visible map"),
        (55, "Eye in the back of your head"),
        (56, "Oops..."),
        (57, "Attack fly"),
        (58, "Temporary invincibility"),
        (60, "Building bridges"),
        (62, "Kills heal"),
        (63, "Stores energy"),
        (64, "50% off"),
        (65, "Summon bombs"),
        (66, "Temporary enemy slowdown"),
        (67, "Friends 'till the end"),
        (68, "Laser tears"),
        (69, "Charge shots"),
        (70, "Speed + DMG up"),
        (71, "Speed + range up"),
        (72, "Tears + faith up"),
        (73, "Gotta meat 'em all"),
        (74, "+25 coins"),
        (75, "Better pills"),
        (76, "I've seen everything"),
        (77, "Temporary badass"),
        (78, "Reusable soul protection"),
        (79, "DMG + speed up"),
        (80, "DMG + tears up"),
        (81, "9 lives"),
        (82, "Demon wings"),
        (83, "Temporary demon form"),
        (84, "Reusable level skip"),
        (85, "Reusable card generator "),
        (86, "Summon Monstro"),
        (87, "Cross tears"),
        (88, "Attack buddy"),
        (89, "Slow effect"),
        (90, "DMG up"),
        (91, "See-through doors"),
        (92, "+2 hearts"),
        (93, "Temporary Man-Pac"),
        (94, "Gives money"),
        (95, "Friends 'till the bbbbzzzt"),
        (96, "Gives kisses"),
        (97, "Reusable item generator"),
        (98, "Soul generator"),
        (99, "Sticky friend"),
        (100, "Psychic friend"),
        (101, "All stats up"),
        (102, "Reusable pill generator"),
        (103, "Poison damage"),
        (104, "Split shot"),
        (105, "Reroll your destiny"),
        (106, "Bigger boom"),
        (107, "Cut and run"),
        (108, "Damage resistance"),
        (109, "$$$ = DMG"),
        (110, "Freeze effect"),
        (111, "Toot on command"),
        (112, "Extra protection"),
        (113, "Auto-turret friend"),
        (114, "Stab stab stab"),
        (115, "Spectral tears"),
        (116, "Quicker charge"),
        (117, "Protective buddy"),
        (118, "Blood laser barrage"),
        (119, "HP up"),
        (120, "Tears + speed up, DMG down"),
        (121, "HP + DMG up, speed down"),
        (122, "Curse up"),
        (123, "Temporary buddy generator"),
        (124, "It's a mystery"),
        (125, "Homing bombs"),
        (126, "Feel my pain"),
        (127, "I don't remember..."),
        (128, "Attack fly"),
        (129, "HP up"),
        (130, "Flight + dash attack"),
        (131, "Gives bombs"),
        (132, "My Xmas present"),
        (133, "Soul converter"),
        (134, "Cursed?"),
        (135, "Portable blood bank"),
        (136, "Friends 'till the end"),
        (137, "Remote bomb detonation"),
        (138, "DMG + HP up"),
        (139, "More trinket room"),
        (140, "+5 poison bombs"),
        (141, "Ultimate grand supreme"),
        (142, "Pray for a miracle"),
        (143, "Speed + shot speed up"),
        (144, "He's greedy"),
        (145, "Reusable fly hive"),
        (146, "Reusable eternity "),
        (147, "Rocks don't stand a chance"),
        (148, "Fly revenge"),
        (149, "Explosive shots"),
        (150, "Tooth shot"),
        (151, "They grow inside"),
        (152, "Extra laser"),
        (153, "Quad shot"),
        (154, "DMG up"),
        (155, "Plop!"),
        (156, "Item martyr"),
        (157, "RAGE!"),
        (158, "I see my future"),
        (159, "Scary"),
        (160, "Holy white death"),
        (161, "Eternal life?"),
        (162, "Blessing of protection"),
        (163, "Spectral buddy"),
        (164, "Reusable flames"),
        (165, "Shot speed + damage up"),
        (166, "Reroll the basics"),
        (167, "Double shot buddy"),
        (168, "On-demand air strike"),
        (169, "Mega tears"),
        (170, "Daddy's love"),
        (171, "Mass enemy slowdown + damage"),
        (172, "My fate protects me"),
        (173, "Blessing of purity"),
        (174, "Random buddy"),
        (175, "Opens all doors..."),
        (176, "HP + shot speed up"),
        (177, "Gamble 24/7"),
        (178, "Splash!"),
        (179, "Flight eternal"),
        (180, "Toot on touch"),
        (181, "Flight + holy death"),
        (182, "Homing shots + DMG up"),
        (183, "Tears + shot speed up"),
        (184, "Flight + HP up"),
        (185, "Flight + spectral tears"),
        (186, "Mass enemy damage at a cost"),
        (187, "Swing it"),
        (188, "Mirrored buddy"),
        (189, "All stats up"),
        (190, "99 bombs"),
        (191, "Rainbow tears"),
        (192, "Temporary psychic shot"),
        (193, "DMG + HP up"),
        (194, "Shot speed up"),
        (195, "What's all this...?"),
        (196, "Tears up"),
        (197, "Damage + range up"),
        (198, "Stuff"),
        (199, "Better chest loot +2 keys"),
        (200, "Charm tears"),
        (201, "DMG up + concussive tears"),
        (202, "Golden touch"),
        (203, "1+1 free 4Evar"),
        (204, "Filled with goodies"),
        (205, "Infinite charge... at a cost"),
        (206, "DMG + tears up. An out-of-body experience!"),
        (207, "Gotta lick 'em all!"),
        (208, "DMG + challenge up"),
        (209, "Toxic blast +5 bombs"),
        (210, "Unbreakable"),
        (211, "Spider revenge"),
        (212, "Eternal life?"),
        (213, "Shielded tears"),
        (214, "Toxic blood"),
        (215, "He accepts your offering"),
        (216, "DMG + evil up"),
        (217, "You feel itchy..."),
        (218, "Regeneration + HP up"),
        (219, "HP up"),
        (220, "Tear blasts +5 bombs"),
        (221, "Bouncing tears"),
        (222, "Anti-gravity tears + tears up"),
        (223, "It hurts so good +5 bombs"),
        (224, "Bursting shots + tears up"),
        (225, "Sweet suffering"),
        (226, "HP up x3"),
        (227, "My life savings"),
        (228, "Fear shot + tears up"),
        (229, "Charged burst attack"),
        (230, "Evil + DMG up + fear shot"),
        (231, "Sticky feet..."),
        (232, "Let's slow this down a bit..."),
        (233, "Orbiting tears + range up"),
        (234, "Infestation shot"),
        (236, "Turdy touch"),
        (237, "Piercing shots + DMG up"),
        (238, "???"),
        (239, "???"),
        (240, "Some stats up, some stats down"),
        (241, "Wealth... but at what cost?"),
        (242, "Blocks damage... sometimes"),
        (243, "You feel guarded"),
        (244, "It's still being tested..."),
        (245, "Double shot"),
        (246, "Secrets"),
        (247, "Your friends rule"),
        (248, "Giant spiders and flies"),
        (249, "More options"),
        (250, "1+1 BOOM!"),
        (251, "Extra card room"),
        (252, "Extra pill room"),
        (253, "HP + luck up"),
        (254, "DMG + range up"),
        (255, "Tears + shot speed up"),
        (256, "Burning blast +5 bombs"),
        (257, "Flaming tears"),
        (258, "Syntax error"),
        (259, "DMG up + fear shot"),
        (260, "Curse immunity + evil up"),
        (261, "Short range mega tears"),
        (262, "Evil up. Your enemies will pay!"),
        (263, "Rune mimic"),
        (264, "Revenge fly"),
        (265, "Immortal friend"),
        (266, "Sticky babies"),
        (267, "We worked out all the kinks"),
        (268, "Infested friend"),
        (269, "Bloody friend"),
        (270, "Blood sucker"),
        (271, "?"),
        (272, "Big Beautiful Fly"),
        (273, "Explosive thoughts"),
        (274, "Sworn protector"),
        (275, "Evil friend"),
        (276, "Protect it"),
        (277, "Fear him"),
        (278, "He wants to take your life"),
        (279, "Fat protector"),
        (280, "She loves you"),
        (281, "Scape goat"),
        (282, "It's time you learned how"),
        (283, "REEROLLLLL!"),
        (284, "Reroll into something else"),
        (285, "Reroll enemies"),
        (286, "Card mimic"),
        (287, "Tome of knowledge"),
        (288, "It's a box of spiders"),
        (289, "Flame on"),
        (290, "Save your life"),
        (291, "..."),
        (292, "Reusable evil... but at what cost?"),
        (293, "Krampus rage"),
        (294, "Reusable knock-back"),
        (295, "Pay to win"),
        (296, "Convert your soul"),
        (297, "? ?"),
        (298, "You feel stumped"),
        (299, "Speed down + rage is building"),
        (300, "Ramming speed"),
        (301, "HP up + you feel protected"),
        (302, "Stompy"),
        (303, "You feel refreshed and protected"),
        (304, "You feel balanced"),
        (305, "Poison tears"),
        (306, "Piercing shots + speed up"),
        (307, "All stats up"),
        (308, "Trail of tears"),
        (309, "Tears up + knock-back shot"),
        (310, "DMG up, tears + shot speed down"),
        (311, "Sweet revenge"),
        (312, "HP up + you feel healthy"),
        (313, "Holy shield"),
        (314, "HP up + speed down + you feel stompy"),
        (315, "Magnetic tears"),
        (316, "Cursed charge shot"),
        (317, "Toxic splash damage"),
        (318, "Conjoined friend"),
        (319, "Near-sighted friend"),
        (320, "Controlled friend"),
        (321, "The ol' ball and chain"),
        (322, "Mongo friend"),
        (323, "Collected tears"),
        (324, "Undefined"),
        (325, "Lose your head"),
        (326, "Invincibility at a cost"),
        (327, "Fate chosen"),
        (328, "Fate chosen"),
        (329, "Controlled tears"),
        (330, "DMG down + tears way up"),
        (331, "God tears"),
        (332, "Eternal life?"),
        (333, "I know all"),
        (334, "I feel all"),
        (335, "I am all"),
        (336, "Toxic aura tears"),
        (337, "I think it's broken"),
        (338, "It will never leave you"),
        (339, "Evil + range + shot speed up"),
        (340, "Speed up + size down"),
        (341, "Tears + shot speed up"),
        (342, "HP + tears up + shot speed down"),
        (343, "Luck up"),
        (344, "Evil up"),
        (345, "DMG + range up"),
        (346, "HP up"),
        (347, "Double item vision"),
        (348, "Pill mimic"),
        (349, "Flip a coin"),
        (350, "Mass poison"),
        (351, "Giga fart!"),
        (352, "Be gentle..."),
        (353, "Cross blast + 5 bombs"),
        (354, "HP up. Don't swallow the prize!"),
        (355, "Range + luck up"),
        (356, "Active power up"),
        (357, "Double your friends"),
        (358, "Double wiz shot!"),
        (359, "Stick it to 'em!"),
        (360, "Dark friend"),
        (361, "Your fate beside you"),
        (362, "What's in the box?"),
        (363, "Protective friend"),
        (364, "Friendly fly"),
        (365, "Lost protector"),
        (366, "We put bombs in your bombs!"),
        (367, "Egg sack bombs!"),
        (368, "Intensifying tears"),
        (369, "Transcendent tears"),
        (370, "Range + tears up"),
        (371, "Embrace chaos"),
        (372, "Bbbzzzzzt! "),
        (373, "Accuracy brings power"),
        (374, "Holy death shot"),
        (375, "Blast resistance"),
        (376, "Never ending stores!"),
        (377, "Spider love"),
        (378, "Uh oh..."),
        (379, "Wide shot"),
        (380, "Money talks"),
        (381, "Tears up + your future shines brighter"),
        (382, "Gotta fetch 'em all!"),
        (383, "Remote tear detonation"),
        (384, "A gurd of your own!"),
        (385, "Bumbo want coin!"),
        (386, "Rerolls rocks"),
        (387, "Peace be with you"),
        (388, "He wants your keys!"),
        (389, "Rune generator"),
        (390, "Sworn friend"),
        (391, "Turn your enemy"),
        (392, "The heavens will change you"),
        (393, "The kiss of death"),
        (394, "Directed tears"),
        (395, "Laser ring tears"),
        (396, "Short cutter"),
        (397, "Controlled tears"),
        (398, "Shrink shot!"),
        (399, "Consume thy enemy!"),
        (400, "Your destiny"),
        (401, "Sticky bomb shot"),
        (402, "!!!"),
        (403, "Mod buddy"),
        (404, "He farts"),
        (405, "Double tap glitch"),
        (406, "Reroll stats"),
        (407, "Aura stat boost"),
        (408, "Call to the void"),
        (409, "I reward an empty vessel"),
        (410, "Eye shot"),
        (411, "Their blood brings rage!"),
        (412, "Feed them hate"),
        (413, "Feed them love"),
        (414, "There's options"),
        (415, "The untainted gain power"),
        (416, "More money!"),
        (417, "Damage booster"),
        (418, "Rainbow effects!"),
        (419, "I-Teleport!"),
        (420, "Spin the black circle!"),
        (421, "Love toots"),
        (422, "Turn back time"),
        (423, "Protect me from myself"),
        (424, "More sacks!"),
        (425, "Scared of the dark?"),
        (426, "Follows my every move..."),
        (427, "Booom!"),
        (428, "You feel cozy"),
        (429, "Penny tears"),
        (430, "Turret follower"),
        (431, "ydduB Buddy"),
        (432, "Prize bombs"),
        (433, "Me! And my shaaaadow!"),
        (434, "Bug catcher"),
        (435, "4-way buddy!"),
        (436, "Don't cry over it..."),
        (437, "Roll again"),
        (438, "Tears up"),
        (439, "What's inside?"),
        (440, "Matt's kidney stone"),
        (441, "Laser breath"),
        (442, "Loss is power"),
        (443, "Trick or treat?"),
        (444, "He's a bleeder!"),
        (445, "Bark at the moon!"),
        (446, "Toxic breath"),
        (447, "Crying makes me toot"),
        (448, "Blood and guts!"),
        (449, "It itches..."),
        (450, "Gold tears!"),
        (451, "I see the future"),
        (452, "I'm leaking..."),
        (453, "Bone tears!"),
        (454, "Hold me!"),
        (455, "I remember this..."),
        (456, "HP up"),
        (457, "Hard headed!"),
        (458, "What's in there?"),
        (459, "Booger tears!"),
        (460, "Blind tears!"),
        (461, "Egg tears!"),
        (462, "Possessed tears!"),
        (463, "Acid tears!"),
        (464, "A gift from above"),
        (465, "360 tears!"),
        (466, "Outbreak!"),
        (467, "Watch where you point that!"),
        (468, "It follows"),
        (469, ":("),
        (470, "Lil hush!"),
        (471, "Ain't he cute?"),
        (472, "Hail to the king baby"),
        (473, "Chub chub"),
        (474, "You broke it!"),
        (475, "My last resort"),
        (476, "What will it be?"),
        (477, "Consume"),
        (478, "Stop!"),
        (479, "Trinket melter!"),
        (480, "Gain more friends!"),
        (481, "109"),
        (482, "Change"),
        (483, "BOOOOOOOOOM!"),
        (484, "I can't believe it's not butter bean!"),
        (485, "50/50"),
        (486, "I feel numb..."),
        (487, "A pound of flesh..."),
        (488, "Waggles a finger"),
        (489, "Reroll forever"),
        (490, "..."),
        (491, "Pills pills pills!"),
        (492, "Yo listen!"),
        (493, "Panic = power"),
        (494, "Electric tears"),
        (495, "Flame tears"),
        (496, "Needle shot"),
        (497, "Camo kid"),
        (498, "You feel very balanced"),
        (499, "Peace be with you"),
        (500, "Gives sacks"),
        (501, "Money = health!"),
        (502, "Creep shots"),
        (503, "Big brother is watching"),
        (504, "Friendly fly"),
        (505, "Gotta catch em..."),
        (506, "Watch your back!"),
        (507, "More blood!"),
        (508, "It's sharp!"),
        (509, "Bloody friend"),
        (510, "Unleash the power!"),
        (511, "He's violent"),
        (512, "Nothing can escape"),
        (513, "Party time!"),
        (514, "Lag!"),
        (515, "Wrapped up nice for you!"),
        (516, "Sprinkles."),
        (517, "Rapid bomb drops"),
        (518, "What could it be?!"),
        (519, "Delirious friend"),
        (520, "Bloody recharge"),
        (521, "Allow 6 weeks for delivery"),
        (522, "Power of the mind"),
        (523, "Pack and unpack"),
        (524, "Static tears"),
        (525, "You're tearing me apart!"),
        (526, "Lil harbingers!"),
        (527, "Caaan do!"),
        (528, "Eclipsed by the moon"),
        (529, "Eyeball tears"),
        (530, "Just hope you're not next..."),
        (531, "I'm seeing red..."),
        (532, "Feed them!"),
        (533, "Smite thy enemy"),
        (534, "Extra active item room"),
        (535, "You feel safe"),
        (536, "He demands a sacrifice"),
        (537, "Puking buddy"),
        (538, "Choking hazard"),
        (539, "Sacrificial insemination"),
        (540, "Skipping tears"),
        (541, "HP up?"),
        (542, "Projectile shield"),
        (543, "Portable sanctuary"),
        (544, "Stabbing time"),
        (545, "Rise from the grave"),
        (546, "Father's blessing"),
        (547, "Tears up + you feel empty"),
        (548, "Fetch!"),
        (549, "Everything hurts"),
        (550, "It feels cursed"),
        (551, "It feels cursed"),
        (552, "Lost but not forgotten"),
        (553, "Spore shot"),
        (554, "4me"),
        (555, "Pain from gain"),
        (556, "Temporary demon form"),
        (557, "Reusable fortunes"),
        (558, "More eyes"),
        (559, "Zap!"),
        (560, "No it doesn't..."),
        (561, "DMG down + tears up + you feel nutty"),
        (562, "It's only up from there"),
        (563, "Random blast +5 bombs"),
        (564, "Tears + shot speed up"),
        (565, "What a cute little thing!"),
        (566, "Sweet dreams"),
        (567, "Keep the flame burning"),
        (568, "Double tap shield"),
        (569, "Bleed me dry"),
        (570, "Tasty rainbow"),
        (571, "Speed up + your feet feel stronger"),
        (572, "DMG up + range up + controlled tears"),
        (573, "Halo of tears"),
        (574, "Purifying light"),
        (575, "Invasive friend"),
        (576, "Filthy friends"),
        (577, "A king's fortune... but at what cost?"),
        (578, "Party time!"),
        (579, "Divine blade"),
        (580, "Explore the other side"),
        (581, "Flamboyant protector"),
        (582, "Tears up. A mind changing experience!"),
        (583, "Rocket propulsion +5 bombs"),
        (584, "Spiritual companionship"),
        (585, "A sacred offering"),
        (586, "May you get what you came for"),
        (588, "Radiant victory"),
        (589, "The moon's blessing shines upon you"),
        (590, "Speed up + you feel elusive"),
        (591, "HP up + you feel pretty"),
        (592, "Born to rock"),
        (593, "Double tap dash"),
        (594, "You're a gas giant!"),
        (595, "Ring of tears"),
        (596, "Ice tears"),
        (597, "Open the floodgates"),
        (598, "Size down"),
        (599, "Extra curse rooms"),
        (600, "Tears up"),
        (601, "Tears up, you feel forgiven"),
        (602, "Exclusive access!"),
        (603, "Instant energy!"),
        (604, "Mother's strength"),
        (605, "Plop!"),
        (606, "Stare into the abyss"),
        (607, "Messy friend"),
        (608, "Iced iced baby"),
        (609, "???"),
        (610, "Fat buddy"),
        (611, "Hear my pain"),
        (612, "Protect him"),
        (614, "Bloody blast + HP up"),
        (615, "Puffy buddy"),
        (616, "It burns"),
        (617, "Magnetizing tears"),
        (618, "Delicious!"),
        (619, "???"),
        (621, "Full HP + temporary DMG up"),
        (622, "In the beginning"),
        (623, "Open your enemies"),
        (624, "Collect them all!"),
        (625, "I'm a big boy now!"),
        (626, "???"),
        (627, "???"),
        (628, "Where am I?"),
        (629, "Defense drone"),
        (631, "Slice but no dice"),
        (632, "Luck up + you feel protected"),
        (633, "Ascended"),
        (634, "Help from beyond"),
        (635, "Bait and switch"),
        (636, "Time to start over"),
        (637, "They pack a punch!"),
        (638, "Erase thy enemy"),
        (639, "Gross!"),
        (640, "Unleash their sorrow"),
        (641, "Spill your guts"),
        (642, "All your desires fulfilled"),
        (643, "Awaken your faith"),
        (644, "+1 to lowest stat"),
        (645, "Itching for revenge"),
        (646, "Demon blast +5 bombs"),
        (647, "Beat the juice out of them!"),
        (649, "Bouncy friend"),
        (650, "Play time!"),
        (651, "Follow the light"),
        (652, "Kick it!"),
        (653, "Begone!"),
        (654, "Worse pills + evil up"),
        (655, "Let it rip!"),
        (656, "A king's fortune... but at what cost?"),
        (657, "Clogged enemies"),
        (658, "Micro friends"),
        (659, "Tear size + range up"),
        (660, "A link to your future"),
        (661, "They lurk inside"),
        (663, "You feel prickly"),
        (664, "All you can eat"),
        (665, "An eye for secrets"),
        (667, "A helping hand"),
        (668, "..."),
        (669, "All stats up"),
        (670, "There might be options"),
        (671, "Power of love"),
        (672, "Blood money"),
        (673, "Deliver me from evil"),
        (674, "Unfinished business"),
        (675, "Shards of knowledge"),
        (676, "It multiplies"),
        (677, "The true out-of-body experience!"),
        (678, "Fetus shots"),
        (679, "Abyssal friend"),
        (680, "Oh no..."),
        (681, "It hungers"),
        (682, "Clingy buddy"),
        (683, "Break your enemies"),
        (684, "Out for blood"),
        (685, "Your faith grows"),
        (686, "Power of faith"),
        (687, "Best friends forever!"),
        (688, "Let him free"),
        (689, "?????"),
        (690, "Bounce away!"),
        (691, "Destined for greatness"),
        (692, "He awaits your offering"),
        (693, "Infest"),
        (694, "Eternal sorrow"),
        (695, "May your rage bring haste"),
        (696, "Divine protection"),
        (697, "He wants revenge"),
        (698, "Double trouble!"),
        (699, "Ancient power"),
        (700, "I can see see the future future future"),
        (701, "Buried memories"),
        (702, "Hot blooded"),
        (703, "Lost brother"),
        (704, "Rip and tear"),
        (705, "One with the shadows"),
        (706, "Come forth from the depths"),
        (707, "HP up"),
        (708, "DMG up"),
        (709, "Angel breaker"),
        (710, "Make your destiny"),
        (711, "Life and death"),
        (712, "Item summoner"),
        (713, "Return"),
        (714, "Come back"),
        (715, "Saved for later"),
        (716, "Spending power"),
        (717, "Under a rock"),
        (719, "Portable shop"),
        (720, "Anything is possible"),
        (
            721,
            "Isaac and his mother lived alone in a small house on a hill"
        ),
        (722, "Repent"),
        (723, "-1"),
        (724, "Thick blooded"),
        (725, "Your stomach rumbles"),
        (726, "Double tap sneeze"),
        (727, "Spooky blast +5 bombs"),
        (728, "Demonic gestation"),
        (729, "Chuck away!"),
        (730, "DMG + luck up"),
        (731, "DMG + range up"),
        (732, "DMG up")
    ]);
}

lazy_static! {
    pub static ref ITEM_NAMES: HashMap<i32, &'static str> = map!([
        (1, "The Sad Onion"),
        (2, "The Inner Eye"),
        (3, "Spoon Bender"),
        (4, "Cricket's Head"),
        (5, "My Reflection"),
        (6, "Number One"),
        (7, "Blood of the Martyr"),
        (8, "Brother Bobby"),
        (9, "Skatole"),
        (10, "Halo of Flies"),
        (11, "1up!"),
        (12, "Magic Mushroom"),
        (13, "The Virus"),
        (14, "Roid Rage"),
        (15, "<3"),
        (16, "Raw Liver"),
        (17, "Skeleton Key"),
        (18, "A Dollar"),
        (19, "Boom!"),
        (20, "Transcendence"),
        (21, "The Compass"),
        (22, "Lunch"),
        (23, "Dinner"),
        (24, "Dessert"),
        (25, "Breakfast"),
        (26, "Rotten Meat"),
        (27, "Wooden Spoon"),
        (28, "The Belt"),
        (29, "Mom's Underwear"),
        (30, "Mom's Heels"),
        (31, "Mom's Lipstick"),
        (32, "Wire Coat Hanger"),
        (33, "The Bible"),
        (34, "The Book of Belial"),
        (35, "The Necronomicon"),
        (36, "The Poop"),
        (37, "Mr. Boom"),
        (38, "Tammy's Head"),
        (39, "Mom's Bra"),
        (40, "Kamikaze!"),
        (41, "Mom's Pad"),
        (42, "Bob's Rotten Head"),
        (44, "Teleport!"),
        (45, "Yum Heart"),
        (46, "Lucky Foot"),
        (47, "Doctor's Remote"),
        (48, "Cupid's Arrow"),
        (49, "Shoop da Whoop!"),
        (50, "Steven"),
        (51, "Pentagram"),
        (52, "Dr. Fetus"),
        (53, "Magneto"),
        (54, "Treasure Map"),
        (55, "Mom's Eye"),
        (56, "Lemon Mishap"),
        (57, "Distant Admiration"),
        (58, "Book of Shadows"),
        (60, "The Ladder"),
        (62, "Charm of the Vampire"),
        (63, "The Battery"),
        (64, "Steam Sale"),
        (65, "Anarchist Cookbook"),
        (66, "The Hourglass"),
        (67, "Sister Maggy"),
        (68, "Technology"),
        (69, "Chocolate Milk"),
        (70, "Growth Hormones"),
        (71, "Mini Mush"),
        (72, "Rosary"),
        (73, "Cube of Meat"),
        (74, "A Quarter"),
        (75, "PHD"),
        (76, "X-Ray Vision"),
        (77, "My Little Unicorn"),
        (78, "Book of Revelations"),
        (79, "The Mark"),
        (80, "The Pact"),
        (81, "Dead Cat"),
        (82, "Lord of the Pit"),
        (83, "The Nail"),
        (84, "We Need To Go Deeper!"),
        (85, "Deck of Cards"),
        (86, "Monstro's Tooth"),
        (87, "Loki's Horns"),
        (88, "Little Chubby"),
        (89, "Spider Bite"),
        (90, "The Small Rock"),
        (91, "Spelunker Hat"),
        (92, "Super Bandage"),
        (93, "The Gamekid"),
        (94, "Sack of Pennies"),
        (95, "Robo-Baby"),
        (96, "Little C.H.A.D."),
        (97, "The Book of Sin"),
        (98, "The Relic"),
        (99, "Little Gish"),
        (100, "Little Steven"),
        (101, "The Halo"),
        (102, "Mom's Bottle of Pills"),
        (103, "The Common Cold"),
        (104, "The Parasite"),
        (105, "The D6"),
        (106, "Mr. Mega"),
        (107, "The Pinking Shears"),
        (108, "The Wafer"),
        (109, "Money = Power"),
        (110, "Mom's Contacts"),
        (111, "The Bean"),
        (112, "Guardian Angel"),
        (113, "Demon Baby"),
        (114, "Mom's Knife"),
        (115, "Ouija Board"),
        (116, "9 Volt"),
        (117, "Dead Bird"),
        (118, "Brimstone"),
        (119, "Blood Bag"),
        (120, "Odd Mushroom"),
        (121, "Odd Mushroom"),
        (122, "Whore of Babylon"),
        (123, "Monster Manual"),
        (124, "Dead Sea Scrolls"),
        (125, "Bobby-Bomb"),
        (126, "Razor Blade"),
        (127, "Forget Me Now"),
        (128, "Forever Alone"),
        (129, "Bucket of Lard"),
        (130, "A Pony"),
        (131, "Bomb Bag"),
        (132, "A Lump of Coal"),
        (133, "Guppy's Paw"),
        (134, "Guppy's Tail"),
        (135, "IV Bag"),
        (136, "Best Friend"),
        (137, "Remote Detonator"),
        (138, "Stigmata"),
        (139, "Mom's Purse"),
        (140, "Bob's Curse"),
        (141, "Pageant Boy"),
        (142, "Scapular"),
        (143, "Speed Ball"),
        (144, "Bum Friend"),
        (145, "Guppy's Head"),
        (146, "Prayer Card"),
        (147, "Notched Axe"),
        (148, "Infestation"),
        (149, "Ipecac"),
        (150, "Tough Love"),
        (151, "The Mulligan"),
        (152, "Technology 2"),
        (153, "Mutant Spider"),
        (154, "Chemical Peel"),
        (155, "The Peeper"),
        (156, "Habit"),
        (157, "Bloody Lust"),
        (158, "Crystal Ball"),
        (159, "Spirit of the Night"),
        (160, "Crack the Sky"),
        (161, "Ankh"),
        (162, "Celtic Cross"),
        (163, "Ghost Baby"),
        (164, "The Candle"),
        (165, "Cat-o-nine-tails"),
        (166, "D20"),
        (167, "Harlequin Baby"),
        (168, "Epic Fetus"),
        (169, "Polyphemus"),
        (170, "Daddy Longlegs"),
        (171, "Spider Butt"),
        (172, "Sacrificial Dagger"),
        (173, "Mitre"),
        (174, "Rainbow Baby"),
        (175, "Dad's Key"),
        (176, "Stem Cells"),
        (177, "Portable Slot"),
        (178, "Holy Water"),
        (179, "Fate"),
        (180, "The Black Bean"),
        (181, "White Pony"),
        (182, "Sacred Heart"),
        (183, "Tooth Picks"),
        (184, "Holy Grail"),
        (185, "Dead Dove"),
        (186, "Blood Rights"),
        (187, "Guppy's Hairball"),
        (188, "Abel"),
        (189, "SMB Super Fan"),
        (190, "Pyro"),
        (191, "3 Dollar Bill"),
        (192, "Telepathy For Dummies"),
        (193, "MEAT!"),
        (194, "Magic 8 Ball"),
        (195, "Mom's Coin Purse"),
        (196, "Squeezy"),
        (197, "Jesus Juice"),
        (198, "Box"),
        (199, "Mom's Key"),
        (200, "Mom's Eyeshadow"),
        (201, "Iron Bar"),
        (202, "Midas' Touch"),
        (203, "Humbleing Bundle"),
        (204, "Fanny Pack"),
        (205, "Sharp Plug"),
        (206, "Guillotine"),
        (207, "Ball of Bandages"),
        (208, "Champion Belt"),
        (209, "Butt Bombs"),
        (210, "Gnawed Leaf"),
        (211, "Spiderbaby"),
        (212, "Guppy's Collar"),
        (213, "Lost Contact"),
        (214, "Anemic"),
        (215, "Goat Head"),
        (216, "Ceremonial Robes"),
        (217, "Mom's Wig"),
        (218, "Placenta"),
        (219, "Old Bandage"),
        (220, "Sad Bombs"),
        (221, "Rubber Cement"),
        (222, "Anti-Gravity"),
        (223, "Pyromaniac"),
        (224, "Cricket's Body"),
        (225, "Gimpy"),
        (226, "Black Lotus"),
        (227, "Piggy Bank"),
        (228, "Mom's Perfume"),
        (229, "Monstro's Lung"),
        (230, "Abaddon"),
        (231, "Ball of Tar"),
        (232, "Stop Watch"),
        (233, "Tiny Planet"),
        (234, "Infestation 2"),
        (236, "E. Coli"),
        (237, "Death's Touch"),
        (238, "Key Piece 1"),
        (239, "Key Piece 2"),
        (240, "Experimental Treatment"),
        (241, "Contract from Below"),
        (242, "Infamy"),
        (243, "Trinity Shield"),
        (244, "Tech.5"),
        (245, "20/20"),
        (246, "Blue Map"),
        (247, "BFFS!"),
        (248, "Hive Mind"),
        (249, "There's Options"),
        (250, "BOGO Bombs"),
        (251, "Starter Deck"),
        (252, "Little Baggy"),
        (253, "Magic Scab"),
        (254, "Blood Clot"),
        (255, "Screw"),
        (256, "Hot Bombs"),
        (257, "Fire Mind"),
        (258, "Missing No."),
        (259, "Dark Matter"),
        (260, "Black Candle"),
        (261, "Proptosis"),
        (262, "Missing Page 2"),
        (263, "Clear Rune"),
        (264, "Smart Fly"),
        (265, "Dry Baby"),
        (266, "Juicy Sack"),
        (267, "Robo-Baby 2.0"),
        (268, "Rotten Baby"),
        (269, "Headless Baby"),
        (270, "Leech"),
        (271, "Mystery Sack"),
        (272, "BBF"),
        (273, "Bob's Brain"),
        (274, "Best Bud"),
        (275, "Lil Brimstone"),
        (276, "Isaac's Heart"),
        (277, "Lil Haunt"),
        (278, "Dark Bum"),
        (279, "Big Fan"),
        (280, "Sissy Longlegs"),
        (281, "Punching Bag"),
        (282, "How to Jump"),
        (283, "D100"),
        (284, "D4"),
        (285, "D10"),
        (286, "Blank Card"),
        (287, "Book of Secrets"),
        (288, "Box of Spiders"),
        (289, "Red Candle"),
        (290, "The Jar"),
        (291, "Flush!"),
        (292, "Satanic Bible"),
        (293, "Head of Krampus"),
        (294, "Butter Bean"),
        (295, "Magic Fingers"),
        (296, "Converter"),
        (297, "Pandora's Box"),
        (298, "Unicorn Stump"),
        (299, "Taurus"),
        (300, "Aries"),
        (301, "Cancer"),
        (302, "Leo"),
        (303, "Virgo"),
        (304, "Libra"),
        (305, "Scorpio"),
        (306, "Sagittarius"),
        (307, "Capricorn"),
        (308, "Aquarius"),
        (309, "Pisces"),
        (310, "Eve's Mascara"),
        (311, "Judas' Shadow"),
        (312, "Maggy's Bow"),
        (313, "Holy Mantle"),
        (314, "Thunder Thighs"),
        (315, "Strange Attractor"),
        (316, "Cursed Eye"),
        (317, "Mysterious Liquid"),
        (318, "Gemini"),
        (319, "Cain's Other Eye"),
        (320, "???'s Only Friend"),
        (321, "Samson's Chains"),
        (322, "Mongo Baby"),
        (323, "Isaac's Tears"),
        (324, "Undefined"),
        (325, "Scissors"),
        (326, "Breath of Life"),
        (327, "The Polaroid"),
        (328, "The Negative"),
        (329, "The Ludovico Technique"),
        (330, "Soy Milk"),
        (331, "Godhead"),
        (332, "Lazarus' Rags"),
        (333, "The Mind"),
        (334, "The Body"),
        (335, "The Soul"),
        (336, "Dead Onion"),
        (337, "Broken Watch"),
        (338, "The Boomerang"),
        (339, "Safety Pin"),
        (340, "Caffeine Pill"),
        (341, "Torn Photo"),
        (342, "Blue Cap"),
        (343, "Latch Key"),
        (344, "Match Book"),
        (345, "Synthoil"),
        (346, "A Snack"),
        (347, "Diplopia"),
        (348, "Placebo"),
        (349, "Wooden Nickel"),
        (350, "Toxic Shock"),
        (351, "Mega Bean"),
        (352, "Glass Cannon"),
        (353, "Bomber Boy"),
        (354, "Crack Jacks"),
        (355, "Mom's Pearls"),
        (356, "Car Battery"),
        (357, "Box of Friends"),
        (358, "The Wiz"),
        (359, "8 Inch Nails"),
        (360, "Incubus"),
        (361, "Fate's Reward"),
        (362, "Lil Chest"),
        (363, "Sworn Protector"),
        (364, "Friend Zone"),
        (365, "Lost Fly"),
        (366, "Scatter Bombs"),
        (367, "Sticky Bombs"),
        (368, "Epiphora"),
        (369, "Continuum"),
        (370, "Mr. Dolly"),
        (371, "Curse of the Tower"),
        (372, "Charged Baby"),
        (373, "Dead Eye"),
        (374, "Holy Light"),
        (375, "Host Hat"),
        (376, "Restock"),
        (377, "Bursting Sack"),
        (378, "Number Two"),
        (379, "Pupula Duplex"),
        (380, "Pay To Play"),
        (381, "Eden's Blessing"),
        (382, "Friendly Ball"),
        (383, "Tear Detonator"),
        (384, "Lil Gurdy"),
        (385, "Bumbo"),
        (386, "D12"),
        (387, "Censer"),
        (388, "Key Bum"),
        (389, "Rune Bag"),
        (390, "Seraphim"),
        (391, "Betrayal"),
        (392, "Zodiac"),
        (393, "Serpent's Kiss"),
        (394, "Marked"),
        (395, "Tech X"),
        (396, "Ventricle Razor"),
        (397, "Tractor Beam"),
        (398, "God's Flesh"),
        (399, "Maw of the Void"),
        (400, "Spear of Destiny"),
        (401, "Explosivo"),
        (402, "Chaos"),
        (403, "Spider Mod"),
        (404, "Farting Baby"),
        (405, "GB Bug"),
        (406, "D8"),
        (407, "Purity"),
        (408, "Athame"),
        (409, "Empty Vessel"),
        (410, "Evil Eye"),
        (411, "Lusty Blood"),
        (412, "Cambion Conception"),
        (413, "Immaculate Conception"),
        (414, "More Options"),
        (415, "Crown of Light"),
        (416, "Deep Pockets"),
        (417, "Succubus"),
        (418, "Fruit Cake"),
        (419, "Teleport 2.0"),
        (420, "Black Powder"),
        (421, "Kidney Bean"),
        (422, "Glowing Hour Glass"),
        (423, "Circle of Protection"),
        (424, "Sack Head"),
        (425, "Night Light"),
        (426, "Obsessed Fan"),
        (427, "Mine Crafter"),
        (428, "PJs"),
        (429, "Head of the Keeper"),
        (430, "Papa Fly"),
        (431, "Multidimensional Baby"),
        (432, "Glitter Bombs"),
        (433, "My Shadow"),
        (434, "Jar of Flies"),
        (435, "Lil Loki"),
        (436, "Milk!"),
        (437, "D7"),
        (438, "Binky"),
        (439, "Mom's Box"),
        (440, "Kidney Stone"),
        (441, "Mega Blast"),
        (442, "Dark Prince's Crown"),
        (443, "Apple!"),
        (444, "Lead Pencil"),
        (445, "Dog Tooth"),
        (446, "Dead Tooth"),
        (447, "Linger Bean"),
        (448, "Shard of Glass"),
        (449, "Metal Plate"),
        (450, "Eye of Greed"),
        (451, "Tarot Cloth"),
        (452, "Varicose Veins"),
        (453, "Compound Fracture"),
        (454, "Polydactyly"),
        (455, "Dad's Lost Coin"),
        (456, "Midnight Snack"),
        (457, "Cone Head"),
        (458, "Belly Button"),
        (459, "Sinus Infection"),
        (460, "Glaucoma"),
        (461, "Parasitoid"),
        (462, "Eye of Belial"),
        (463, "Sulfuric Acid"),
        (464, "Glyph of Balance"),
        (465, "Analog Stick"),
        (466, "Contagion"),
        (467, "Finger!"),
        (468, "Shade"),
        (469, "Depression"),
        (470, "Hushy"),
        (471, "Lil Monstro"),
        (472, "King Baby"),
        (473, "Big Chubby"),
        (474, "Broken Glass Cannon"),
        (475, "Plan C"),
        (476, "D1"),
        (477, "Void"),
        (478, "Pause"),
        (479, "Smelter"),
        (480, "Compost"),
        (481, "Dataminer"),
        (482, "Clicker"),
        (483, "Mama Mega!"),
        (484, "Wait What?"),
        (485, "Crooked Penny"),
        (486, "Dull Razor"),
        (487, "Potato Peeler"),
        (488, "Metronome"),
        (489, "D infinity"),
        (490, "Eden's Soul"),
        (491, "Acid Baby"),
        (492, "YO LISTEN!"),
        (493, "Adrenaline"),
        (494, "Jacob's Ladder"),
        (495, "Ghost Pepper"),
        (496, "Euthanasia"),
        (497, "Camo Undies"),
        (498, "Duality"),
        (499, "Eucharist"),
        (500, "Sack of Sacks"),
        (501, "Greed's Gullet"),
        (502, "Large Zit"),
        (503, "Little Horn"),
        (504, "Brown Nugget"),
        (505, "Poke Go"),
        (506, "Backstabber"),
        (507, "Sharp Straw"),
        (508, "Mom's Razor"),
        (509, "Bloodshot Eye"),
        (510, "Delirious"),
        (511, "Angry Fly"),
        (512, "Black Hole"),
        (513, "Bozo"),
        (514, "Broken Modem"),
        (515, "Mystery Gift"),
        (516, "Sprinkler"),
        (517, "Fast Bombs"),
        (518, "Buddy in a Box"),
        (519, "Lil Delirium"),
        (520, "Jumper Cables"),
        (521, "Coupon"),
        (522, "Telekinesis"),
        (523, "Moving Box"),
        (524, "Technology Zero"),
        (525, "Leprosy"),
        (526, "7 Seals"),
        (527, "Mr. ME!"),
        (528, "Angelic Prism"),
        (529, "Pop!"),
        (530, "Death's List"),
        (531, "Haemolacria"),
        (532, "Lachryphagy"),
        (533, "Trisagion"),
        (534, "Schoolbag"),
        (535, "Blanket"),
        (536, "Sacrificial Altar"),
        (537, "Lil Spewer"),
        (538, "Marbles"),
        (539, "Mystery Egg"),
        (540, "Flat Stone"),
        (541, "Marrow"),
        (542, "Slipped Rib"),
        (543, "Hallowed Ground"),
        (544, "Pointy Rib"),
        (545, "Book of the Dead"),
        (546, "Dad's Ring"),
        (547, "Divorce Papers"),
        (548, "Jaw Bone"),
        (549, "Brittle Bones"),
        (550, "Broken Shovel"),
        (551, "Broken Shovel"),
        (552, "Mom's Shovel"),
        (553, "Mucormycosis"),
        (554, "2Spooky"),
        (555, "Golden Razor"),
        (556, "Sulfur"),
        (557, "Fortune Cookie"),
        (558, "Eye Sore"),
        (559, "120 Volt"),
        (560, "It Hurts"),
        (561, "Almond Milk"),
        (562, "Rock Bottom"),
        (563, "Nancy Bombs"),
        (564, "A Bar of Soap"),
        (565, "Blood Puppy"),
        (566, "Dream Catcher"),
        (567, "Paschal Candle"),
        (568, "Divine Intervention"),
        (569, "Blood Oath"),
        (570, "Playdough Cookie"),
        (571, "Orphan Socks"),
        (572, "Eye of the Occult"),
        (573, "Immaculate Heart"),
        (574, "Monstrance"),
        (575, "The Intruder"),
        (576, "Dirty Mind"),
        (577, "Damocles"),
        (578, "Free Lemonade"),
        (579, "Spirit Sword"),
        (580, "Red Key"),
        (581, "Psy Fly"),
        (582, "Wavy Cap"),
        (583, "Rocket in a Jar"),
        (584, "Book of Virtues"),
        (585, "Alabaster Box"),
        (586, "The Stairway"),
        (588, "Sol"),
        (589, "Luna"),
        (590, "Mercurius"),
        (591, "Venus"),
        (592, "Terra"),
        (593, "Mars"),
        (594, "Jupiter"),
        (595, "Saturnus"),
        (596, "Uranus"),
        (597, "Neptunus"),
        (598, "Pluto"),
        (599, "Voodoo Head"),
        (600, "Eye Drops"),
        (601, "Act of Contrition"),
        (602, "Member Card"),
        (603, "Battery Pack"),
        (604, "Mom's Bracelet"),
        (605, "The Scooper"),
        (606, "Ocular Rift"),
        (607, "Boiled Baby"),
        (608, "Freezer Baby"),
        (609, "Eternal D6"),
        (610, "Bird Cage"),
        (611, "Larynx"),
        (612, "Lost Soul"),
        (614, "Blood Bombs"),
        (615, "Lil Dumpy"),
        (616, "Bird's Eye"),
        (617, "Lodestone"),
        (618, "Rotten Tomato"),
        (619, "Birthright"),
        (621, "Red Stew"),
        (622, "Genesis"),
        (623, "Sharp Key"),
        (624, "Booster Pack"),
        (625, "Mega Mush"),
        (626, "Knife Piece 1"),
        (627, "Knife Piece 2"),
        (628, "Death Certificate"),
        (629, "Bot Fly"),
        (631, "Meat Cleaver"),
        (632, "Evil Charm"),
        (633, "Dogma"),
        (634, "Purgatory"),
        (635, "Stitches"),
        (636, "R Key"),
        (637, "Knockout Drops"),
        (638, "Eraser"),
        (639, "Yuck Heart"),
        (640, "Urn of Souls"),
        (641, "Akeldama"),
        (642, "Magic Skin"),
        (643, "Revelation"),
        (644, "Consolation Prize"),
        (645, "Tinytoma"),
        (646, "Brimstone Bombs"),
        (647, "4.5 Volt"),
        (649, "Fruity Plum"),
        (650, "Plum Flute"),
        (651, "Star of Bethlehem"),
        (652, "Cube Baby"),
        (653, "Vade Retro"),
        (654, "False PHD"),
        (655, "Spin to Win"),
        (656, "Damocles"),
        (657, "Vasculitis"),
        (658, "Giant Cell"),
        (659, "Tropicamide"),
        (660, "Card Reading"),
        (661, "Quints"),
        (663, "Tooth and Nail"),
        (664, "Binge Eater"),
        (665, "Guppy's Eye"),
        (667, "Strawman"),
        (668, "Dad's Note"),
        (669, "Sausage"),
        (670, "Options?"),
        (671, "Candy Heart"),
        (672, "A Pound of Flesh"),
        (673, "Redemption"),
        (674, "Spirit Shackles"),
        (675, "Cracked Orb"),
        (676, "Empty Heart"),
        (677, "Astral Projection"),
        (678, "C Section"),
        (679, "Lil Abaddon"),
        (680, "Montezuma's Revenge"),
        (681, "Lil Portal"),
        (682, "Worm Friend"),
        (683, "Bone Spurs"),
        (684, "Hungry Soul"),
        (685, "Jar of Wisps"),
        (686, "Soul Locket"),
        (687, "Friend Finder"),
        (688, "Inner Child"),
        (689, "Glitched Crown"),
        (690, "Belly Jelly"),
        (691, "Sacred Orb"),
        (692, "Sanguine Bond"),
        (693, "The Swarm"),
        (694, "Heartbreak"),
        (695, "Bloody Gust"),
        (696, "Salvation"),
        (697, "Vanishing Twin"),
        (698, "Twisted Pair"),
        (699, "Azazel's Rage"),
        (700, "Echo Chamber"),
        (701, "Isaac's Tomb"),
        (702, "Vengeful Spirit"),
        (703, "Esau Jr."),
        (704, "Berserk!"),
        (705, "Dark Arts"),
        (706, "Abyss"),
        (707, "Supper"),
        (708, "Stapler"),
        (709, "Suplex!"),
        (710, "Bag of Crafting"),
        (711, "Flip"),
        (712, "Lemegeton"),
        (713, "Sumptorium"),
        (714, "Recall"),
        (715, "Hold"),
        (716, "Keeper's Sack"),
        (717, "Keeper's Kin"),
        (719, "Keeper's Box"),
        (720, "Everything Jar"),
        (721, "TMTRAINER"),
        (722, "Anima Sola"),
        (723, "Spindown Dice"),
        (724, "Hypercoagulation"),
        (725, "IBS"),
        (726, "Hemoptysis"),
        (727, "Ghost Bombs"),
        (728, "Gello"),
        (729, "Decap Attack"),
        (730, "Glass Eye"),
        (731, "Stye"),
        (732, "Mom's Ring")
    ]);
}

#[repr(C)]
pub enum Buttons {
    LEFT = 0,
    RIGHT = 1,
    UP = 2,
    DOWN = 3,
    A = 4,
    B = 5,
    X = 6,
    Y = 7,
    L = 8,
    ZL = 9,
    LEFT_STICK = 10,
    R = 11,
    ZR = 12,
    RIGHT_STICK = 13,
}
